language: java
deploy:
  provider: heroku
  api_key:
    secure: X2JmJ+nIOSRZ6eWLZdQTVm1ob8YzJiXk0QLYgsZqtecEVw0FfyGGRNDBszgWNXyW8vMzhVOlCHAZoZMftI9nIMNtLaUByrz0kIuZlwMi8jOxGuE+H6/s2Kr81FShGgaaIGnfgmRxXvqUGZd62MRl5HrkpO4zcPftlvkCSVXBSfK3ITBVd3ukNMW+noO7bNAcuJA9OW0RfJL5cZ7fclp7C8pgWKCQHDuFAwTBRtKd2JSG570yQGI9UJ1J4OfNThwbduzHCmKXJd2D+Fn8xlhMrWDS6krI/UJx9TitZbeTkfdO7+hDDrqloWBG0LdkN9joz18Nmw5ebnfQizaZAiZaLBJMQ+GNeovewMtrtmzZy0b6WyWrG8DlVqrjopjaDe0sUqLOMrTFYC/DHp5kmXMlE1UbYVuhfQ4tg6P+6XU3avoc0VAPKQbb6hgBZXNs1N0wfWC/8vPyeGe5VtT0gl8VnTfGTfaSYtrGj0MEgf/IdareRGczvrvHQ4MVFo7K4yF9sHU8F20SB4GO2GJ7KxE8xoVmXYuMp8+nCSzJcxTfvBlrNmvvEJszSbHO4FkCJOl8jQxznhaKDllscW2eogVyt5Uibo88Z5mDUYyiRx6abVj7HqvTVo/NxNJYRAjWsdJOcf/xBwk7PxRFU1/9mSn/m5gomlr49U3zsBx/3j/aT/U=
  app: devopskevinberg
